CREATE TABLE CUSTOMER (
  CUSTOMER_ID INT NOT NULL AUTO_INCREMENT,
  CUSTOMER_NAME VARCHAR(50) NOT NULL,
  CUSTOMER_EMAIL VARCHAR(250) NOT NULL,
  CUSTOMER_DATE VARCHAR(50) NOT NULL,
  CUSTOMER_PHONE_NUMBER VARCHAR(50) NOT NULL,
  CUSTOMER_DOCUMENT VARCHAR(50) NOT NULL,
  CUSTOMER_GENDER VARCHAR(50) NOT NULL,
  PASSWORD_HASH VARCHAR (250) NOT NULL,
  IMAGE_PATH VARCHAR(250),
  PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE PRODUCT_ITEM (
  PRODUCT_ITEM_ID INT NOT NULL AUTO_INCREMENT,
  CUSTOMER_ID INT NOT NULL,
  PRODUCT_NAME VARCHAR(50) NOT NULL,
  PRICE DECIMAL(10,2) NOT NULL,
  DESCRIPTION VARCHAR(250) NOT NULL,
  IMAGE_PATH VARCHAR(50),
  PRIMARY KEY (PRODUCT_ITEM_ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);
